### ISSUE TITLE
Create Git Tags to Line up with Charts on `hub.helm.sh`

### ISSUE THREAD

**Issue by johnlonganecker** [concourse/concourse-chart#108]
The latest version I see tagged in this repo is `v9.0.0`, but on `hub.helm.sh` I see versions later than that.

It would be helpful for me to be able to line up versions to git commits.

Thanks for working making this project!

**Comment by taylorsilva** [comment]
Done! We started doing that with `11.1.0` of the chart and have it in a pipeline here: https://github.com/concourse/ci/blob/c51e1008bfd407cd202c7da608183deba642497a/pipelines/helm-chart.yml#L62-L63
