### ISSUE TITLE
Versioning in the presence of backports

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse-chart#13]
Hey,

Given that we have two versions for the Helm chart (the version of the chart
itself - i.e., packaging -, as well as the version of the underlying software -
concourse), versioning a backport is quite weird: should we just bump the
`patch` number? Would we end up with collisions? This becomes speciall important
as we create a repository to store all of our chart versions.

What I think we could do, is establish a little process that would allow us to
keep those versions sane without having to spend too much thinking about it:

- backward-incompatible changes that break the contract of interacting with the
  chart mean a bump in major

e.g.: renaming a field in `values.yaml`

- new functionality that is backward-compatible, get a minor
  bump

e.g.: adding a new field to `values.yaml`, or changing certain templates in a
way that doesn't affect any of the interaction

- changes in the underlying version of concourse get a minor bump 
  -  except when backporting: changes in backports always produce a patch
  

e.g.:

```

REGULAR RELEASES

			bump concourse to 5.5.6
			   -----------> 

		before				after

	version: 1.2.3				version: 1.3.0
	appVersion: 5.5.5			appVersion: 5.5.6



"LTS" VERSION (one receiving a backport)



			bump concourse to 5.5.6
			   -----------> 

		before				after

	version: 1.2.3				version: 1.2.4
	appVersion: 5.5.5			appVersion: 5.5.6

```

Wdyt?

I tried deviating the less from semver, but it seems like there a little bit of
compromising that we'd need to do :grimacing:

thanks!

**Comment by pivotal-bin-ju** [comment]
Hi @cirocosta ,
I understand the trickiness between the helm `version` and `appVersion`.
I personal like bumping up the minor version when the appVersion is bumped. In this case we could have room for fixing helm chart bugs. E.g.: after 2 releases, we found a bug from previous helm chart. In this case it would be tough.
```
			bump concourse to 5.5.6
			   -----------> 

	before                        after                             after 2

	 version: 1.2.3		version: 1.2.4 		version:1.2.5 		(after the release)
	appVersion: 5.5.5	appVersion: 5.5.6	appVersion:5.5.7	 |
					 ^					 |
					 |____________________________________ find a helm chart bug

```
 
My thought is keeping the patch version for fixing the bug from helm chart itself, minor version for small change, major version for significant change.

WDYT?

**Comment by taylorsilva** [comment]
Implementing @cirocosta initial suggestion here: https://github.com/concourse/ci/pull/242
