### ISSUE TITLE
Helm3 Support

### ISSUE THREAD

**Issue by adnankobir** [concourse/concourse-chart#139]
are there any plans to support helm3? If there is interest or on-going work, would love to contribute

**Comment by taylorsilva** [comment]
Yes, I want to put some stories together and get the team working on this. It's long overdue. I'm going to try and make some time for this tomorrow, it's near the top of my todo list

**Comment by adnankobir** [comment]
> Yes, I want to put some stories together and get the team working on this. It's long overdue. I'm going to try and make some time for this tomorrow, it's near the top of my todo list

Awesome. Do let me know if I can contribute in any way

**Comment by dcsg** [comment]
Any news on this?

**Comment by taylorsilva** [comment]
I'm going to close this issue because we started tracking our work in this older issue: https://github.com/concourse/concourse-chart/issues/56
