### ISSUE TITLE
`prs` pipeline for `concourse-chart`?

### ISSUE THREAD

**Issue by pivotal-bin-ju** [concourse/concourse-chart#14]
Since we have our own chart repo now, we do not have to go through the process:
 branch [`merged`](https://github.com/concourse/charts/tree/merged)   -> [`helm/charts/stable/concourse`](https://github.com/helm/charts/tree/master/stable/concourse) -> [our master branch](https://github.com/concourse/concourse-chart)

So the code  in legacy branch `maintenance` of `concourse/charts`  does not quite fit to our new repo.  e.g.: the pipeline [`reconfigure`]( https://github.com/concourse/ci/blob/master/pipelines/reconfigure.yml)

In `concourse/concourse` when a new PR is drafted the pipeline `prs` is going to do the test against the PR and update the PR status after the test is accomplished.

Do we need the similar stuff for helm?

**Comment by taylorsilva** [comment]
Closing since https://github.com/pivotal/concourse-ops/issues/150 covers this.
