### ISSUE TITLE
What kind of list?

### ISSUE THREAD

**Issue by steadysupply** [concourse/concourse-chart#145]
https://github.com/concourse/concourse-chart/blob/5d9c6e46e5bf81e67a02a8e7ac1e4b63dadcd485/values.yaml#L2261-L2263

mentions a list

https://github.com/concourse/concourse-chart/blob/5d9c6e46e5bf81e67a02a8e7ac1e4b63dadcd485/templates/web-secrets.yaml#L37

 but the value is just encoded and sent along.

I assume the "list" is comma-separated or some such?

**Comment by chenbh** [comment]
@steadysupply yeah, it's comma separated `user1:pass1,user2:pass2`. 

Please see https://concourse-ci.org/local-auth.html, the secret gets used by: https://github.com/concourse/concourse-chart/blob/5d9c6e46e5bf81e67a02a8e7ac1e4b63dadcd485/templates/web-deployment.yaml#L223-L227

**Comment by taylorsilva** [comment]
We could add an example here to make it clear what format is expected. The key directly above `localUsers` has an example:
https://github.com/concourse/concourse-chart/blob/5d9c6e46e5bf81e67a02a8e7ac1e4b63dadcd485/values.yaml#L2248-L2259

**Comment by steadysupply** [comment]
Made a PR to push this through.
