### ISSUE TITLE
Missing update chart version

### ISSUE THREAD

**Issue by oo00spy00oo** [concourse/concourse-chart#155]
The version of the chart still in 13.0.0 and Helm cannot get the new version of Concourse CI's  release version 6.6.0

`https://github.com/concourse/concourse-chart/blob/master/Chart.yaml`

**Comment by taylorsilva** [comment]
New version has been released earlier today. Had a minor packaging issue to fix https://github.com/concourse/concourse-chart/commit/c9b5039246f15f658855c3e6db7af7dfcbaaca8d
