### ISSUE TITLE
Concourse akamai issue

### ISSUE THREAD

**Issue by suhail1132** [concourse/concourse-chart#184]
We are running our concourse on AKS. When we try to access our concourse web through akamai from open internet url using common header, we are able to access our concourse akamai url from open internet but we are not able to see the details of triggering pipelines in concourse. It shows the error like this: you are not authorized to view the details of pipelines. I have attached the error screenshot also.
![Screenshot (593)](https://user-images.githubusercontent.com/58470295/100194324-7f390d80-2f1b-11eb-8bac-1ca0d46040ad.png)

**Comment by suhail1132** [comment]
Anu update on this issue?

**Comment by taylorsilva** [comment]
Hey, we have no experience with akami or using CDN's + Concourse in general. I would check the chrome debug console to see if any other errors are being returned. I'm guessing akami is stripping something from the requests but I'm not sure what it would be.

I know people have used nginx/apache as a reverse proxy in front of Concourse without issue. I'm not sure how similar that is to what a CDN does but I'd imagine it means your setup should also work.

**Comment by taylorsilva** [comment]
Theory: akami is caching the build events page and it's doing it via an unauthenticated request, thus the 401 error.

**Comment by taylorsilva** [comment]
Closed because no reply from OP and seems specific to their configuration.
