### ISSUE TITLE
[stable/concourse] Cannot set empty string value for "xFrameOptions"

### ISSUE THREAD

**Issue by kcmannem** [concourse/concourse-chart#22]
We set the value of `xFrameOptions` to an empty string "" in our ci deployment. This allows us to embed example pipelines in our docs page. But helm does not recognize a diff between empty strings and not setting it.

```
+      xFrameOptions: ""
```

but helm diff does not indicate there are any changes to apply.

**Comment by taylorsilva** [comment]
Closing:
https://github.com/concourse/concourse-chart/blob/bfee5dc26ce2713eac925517e41c1e8d1cd8a15b/values.yaml#L717-L719

Our examples page have successfully embedded the example pipelines.
