### ISSUE TITLE
(Question) Adding Concourse repository to Helm

### ISSUE THREAD

**Issue by artamonovkirill** [concourse/concourse-chart#23]
I see that README still states to install Concourse via `helm install stable/concourse`.

Are releases then still being published to https://kubernetes-charts.storage.googleapis.com or should I add a new repository to my Helm installation?

**Comment by Typositoire** [comment]
I ended up adding it as a submodule for now to our automation but yeah either publishing it to stable OR having it's own repo would be awesome. Right now this chart is kind of in an in between and it's not cool :/

**Comment by taylorsilva** [comment]
Updated the README to reference our chart repo at https://concourse-charts.storage.googleapis.com/ with `concourse/concourse`. Let us know if there are any issues.

**Comment by artamonovkirill** [comment]
:+1: 
Will try out Monday.
