### ISSUE TITLE
Is it possible to tag different workers differently?

### ISSUE THREAD

**Issue by dlbock** [concourse/concourse-chart#263]
The way that the `concourse.worker.env` is use right now either in the `worker-deployment.yaml` or `worker-statefulset.yaml` is setting the same values for every worker.

How do we set different env values for different workers? Specifically for [tags](https://github.com/concourse/concourse-chart/blob/master/templates/_helpers.tpl#L160-L163), if we want to have different workers segmented for different things, as the [documentation](https://concourse-ci.org/concourse-worker.html#tagging-workers) implies we should be able to do.

**Comment by taylorsilva** [comment]
Separate deployments is one way to achieve this.

For example, we have a few deployments in this repo: https://github.com/concourse/hush-house/tree/master/deployments/with-creds

Each folder represents one deployment. We separated the web (`hush-house` folder) and worker (`workers` folder) pods by deployment. If we wanted a group of tagged workers we would create a new deployment.

**Comment by dlbock** [comment]
AH! Okay, I'll have a look, thanks @taylorsilva ❤️

**Comment by dlbock** [comment]
I'm guessing the extra deployments of the concourse chart will just be spinning up workers and connecting back to the web pods in the main deployment group?
