### ISSUE TITLE
Cut a release to update to concourse v7.5.0

### ISSUE THREAD

**Issue by bodymindarts** [concourse/concourse-chart#271]
According to https://github.com/concourse/concourse/issues/7493 everything is ready to cut a new release.

I am unable to create GitHub releases via concourse at the moment due to https://github.com/concourse/github-release-resource/pull/107 and would really appreciate it to roll out an upgrade.

**Comment by taylorsilva** [comment]
Commit bumped it https://github.com/concourse/concourse-chart/commit/f46b442f4fcc96bc07a1b434649be0d674573f1b
We didn't release it through ci. Did that now: https://ci.concourse-ci.org/teams/main/pipelines/helm-chart/jobs/publish-chart-patch/builds/25
