### ISSUE TITLE
Wrong imageTag for chart

### ISSUE THREAD

**Issue by nickcaballero-mm** [concourse/concourse-chart#30]
Looks like afe43886c238d7c736f61e535dc1054c43bee34b changed the imageTag to a non-existent version of concourse/concourse image.

```
Failed to pull image "concourse/concourse:8.4.1": rpc error: code = Unknown desc = Error reading manifest 8.4.1
```

**Comment by gmrodgers** [comment]
Also encountered this when playing around, "upgrading" to latest fixed the problem for me

**Comment by taylorsilva** [comment]
Woops, sorry about that! Fixing now

**Comment by taylorsilva** [comment]
Fixed the script that does the version updates and manually updated the chart repo.
