### ISSUE TITLE
Installation Failing with Error

### ISSUE THREAD

**Issue by abhishekpareek19** [concourse/concourse-chart#310]
$ helm install my-release concourse/concourse
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "PodDisruptionBudget" in version "policy/v1"

**Comment by davidkuster** [comment]
@abhishekpareek19 what's your k8s cluster version?

Seeing this on a k8s cluster running v1.19.9. Doing a bit of research and found [this info](https://innablr.com.au/blog/what-is-pod-disruption-budget-in-k8s-and-why-to-use-it/):
> pdb stands for PodDisruptionBudget. Kubernetes API introduced this resource in the initial release of version 1.0. The API remained fairly stable until version 1.21, when it was graduated and promoted to policy/v1 from policy/v1beta1. policy/v1beta1 is currently deprecated, and will be removed in version 1.25.

[worker-policy.yaml](https://github.com/concourse/concourse-chart/blob/8be55cc651c5069685a59ae672d2169bfc39a147/templates/worker-policy.yaml) in this chart specifies the following:
```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
```
Seems it's presuming a cluster version >= 1.21 is being used.

**Comment by wiegandf** [comment]
Above is true for PDBs (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#poddisruptionbudget-v1-policy) but not for PodSecurityPolicies changed in https://github.com/concourse/concourse-chart/commit/ade9143b9c3d4c427fd9ddc71f7a3db377f4cdf1. See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#podsecuritypolicy-v1beta1-policy - there is no podsecuritypolicy in `policy/v1`.

I think this needs to be reverted.
