### ISSUE TITLE
concourse chart is outdated (bump to 7.10.0)

### ISSUE THREAD

**Issue by flokli** [concourse/concourse-chart#343]
### Describe the bug

I recently bumped nixpkgs, which is what I use to get the `fly` cli.

It got bumped to 7.10.0, which isn't compatible with the version of concourse provided with this chart (concourse version 7.9.0).

Would you consider updating this chart to a more recent version?

### Reproduction steps

Download fly from nixpkgs or https://github.com/concourse/concourse/releases/download/v7.10.0/fly-7.10.0-linux-amd64.tgz

Point it to a Concourse 7.9.0 cluster, either created by this helm chart or otherwise

### Expected behavior

The latest concourse release is also what's installed by the helm chart, and the fly tool is compatible.

**Comment by jschaul** [comment]
Chart got updated to 7.11 it seems, so this issue can be closed.

**Comment by flokli** [comment]
For posterity: The chart bump to 7.11.0 happened in https://github.com/concourse/concourse-chart/pull/352.
