### ISSUE TITLE
If web.auth.mainTeam.config is empty helm chart errors out

### ISSUE THREAD

**Issue by d-likes-it** [concourse/concourse-chart#50]
Therefore the default install as described in the README is not working. 

Reproduce:
Follow README for basic install.

Reason: 
no default value of ifs around last 2 lines in tempates/web-configmap.yml.

**Comment by d-likes-it** [comment]
Some more details:

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T20:56:50Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}



with unpacked concourse-9.0.0.tgz:

$ helm install --namespace test concourse-test .
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [unknown object type "nil" in ConfigMap.data.config-rbac.yml, unknown object type "nil" in ConfigMap.data.main-team.yml]

**Comment by Typositoire** [comment]
Yup hitting this issue, the whole configMap is wrong.

It's missing `{{- if .Values.web.enabled -}}` on top as well as some check to see if values are empty
