### ISSUE TITLE
Installation issue on mac

### ISSUE THREAD

**Issue by larsrnielsen** [concourse/concourse-chart#62]
I am following the readme.md documentation, trying to install Concourse on a Mac. 

helm repo add concourse https://concourse-charts.storage.googleapis.com/
`"concourse" has been added to your repositories`

helm install concourse/concourse
`Error: must either provide a name or specify --generate-name`

Providing a name and --generate-name generates the same error:

helm install concourse/concourse --generate-name
`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [unknown object type "nil" in ConfigMap.data.config-rbac.yml, unknown object type "nil" in ConfigMap.data.main-team.yml]`

helm version
`version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}`

kubectl version
`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}`

So not much luck in installing Concourse.

**Comment by mingxiao** [comment]
Seems like you're running into the issue describe here, https://github.com/concourse/concourse-chart/issues/50

You need to pass in a `values.yml` that specifies the `mainTeam`. If you start with the default values.yaml, https://github.com/concourse/concourse-chart/blob/master/values.yaml

Then edit 
```
        mainTeam:
          config:
          roles:
          - name: owner
            local:
              users: ["test"]
```

This will make the `test` user the owner

You'll also need to configure the rbac to have a non-empty value, I just used:

```
     configRBAC:
       owner:
       - SetTeam
```

Then use your values.yml

`helm install --generate-name -f values.yaml concourse/concourse`
