### ISSUE TITLE
not logs for wrong password attempts and setting log levels

### ISSUE THREAD

**Issue by gowrisankar22** [concourse/concourse-chart#65]
Hello Colleagues,
Why basic auth wrong password attempts are not logged for concourse. I don't find 401 not authorized when I check via `kubectl logs po/concourse-we | grep admin_concourse`.

Also, I am not sure to set multiple log levels. Actually I want to see all the logs `debug, info, error.` 
How to get this?

Below settings will work?
```
   ## Minimum level of logs to see. Possible options: debug, info, error.
    ##
    logLevel: info,debug,error
```

https://github.com/concourse/concourse-chart/blob/master/values.yaml#L149-L151

**Comment by cirocosta** [comment]
Hey @gowrisankar22 ,

With regards to the config, you're expected to supply only one of those values, setting "the bar" for which types of logs to show, e.g.:

- debug displays logs of level debug, info, error
- info displays logs of level info, error
- error displays logs of error

For the failed attempts, they should be appearing in your logs 🤔  

https://github.com/concourse/concourse/blob/3439f7a28cd1296f4fb777327c99926bc03b8e59/skymarshal/skyserver/skyserver.go#L322-L323

e.g., trying a faiked login here, I get:

```json
{
  "timestamp": "2020-01-31T14:38:49.378290900Z",
  "level": "error",
  "source": "atc",
  "message": "atc.sky.token.failed-to-fetch-dex-token",
  "data": {
    "error": "oauth2: cannot fetch token: 401 Unauthorized\nResponse: {\"error\":\"access_denied\",\"error_description\":\"Invalid username or password\"}",
    "session": "6.13"
  }
}
```

although, as you can see, we don't display the name of the offending login

**Comment by gowrisankar22** [comment]
@cirocosta I get the log entry if I do failed login via fly commands but Not via concourse web ui.
This seems to be an issue.

**Comment by taylorsilva** [comment]
Closing this since it's an issue with the Concourse binary and not the chart.
