### ISSUE TITLE
Is this the new "official" place for the Concourse chart?

### ISSUE THREAD

**Issue by aegershman** [concourse/concourse-chart#8]
Hey there-- not trying to pin down absolutes, just trying to do my due diligence; do you all expect the "official" concourse-chart to be hosted out of _this_ repo (now or in the future) rather than the `helm/charts` upstream repo?

Thanks! 👍

**Comment by cirocosta** [comment]
Hey @aegershman ,

yepp, the rationale for it is essentially that we want to be able to backport fixes to certain versions if needed, as well as move along w/ the deprecation of this repository as of Helm 3 (see https://github.com/helm/helm/issues/5892).

It'll also make easier for us to put some guard-rails that better match our view of how testing the chart looks like (e.g., we have some 40+ e2e specs for it that we'd like to run on every PR).

We're still finalizing the details, but that will be communicated more openly soon 😁  

thank you!!
